# Generated by Django 4.2.7 on 2023-11-14 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_student_file_remove_student_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Car',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='price',
            new_name='speed',
        ),
    ]
