# Generated by Django 4.2.7 on 2023-11-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_news_user_alter_news_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_name', models.CharField(max_length=100)),
                ('q_email', models.EmailField(max_length=254)),
                ('q_subject', models.CharField(max_length=1000)),
                ('q_message', models.CharField(max_length=10000000)),
            ],
        ),
    ]
