# Generated by Django 4.2.7 on 2023-11-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_your_news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=1000)),
                ('link', models.URLField()),
                ('summary', models.CharField(max_length=10000000)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
