# Generated by Django 4.2.7 on 2023-11-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_add_your_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_your_news',
            name='image',
            field=models.ImageField(upload_to='static/img'),
        ),
    ]
