# Generated by Django 4.2.7 on 2023-11-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_add_your_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_your_news',
            name='image',
            field=models.ImageField(upload_to='../static/img'),
        ),
    ]
