# Generated by Django 4.2.7 on 2023-11-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_add_your_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_your_news',
            name='image',
            field=models.ImageField(upload_to='ads_image'),
        ),
    ]
