# Generated by Django 5.0.1 on 2024-02-29 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
