# Generated by Django 5.0.1 on 2024-03-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='percent',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
